
override BIN := ../result/vm_preparator
override SRC := src/vm_preparator.cpp

$(BIN): $(SRC)
	$(_CXX) $(SRC) -o $(BIN) -std=c++20 -O0
#No optimization because the compilation already runs long enough

clean:
